#!/usr/bin/env python3
#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#

"""Validate the optional exact-source Merlin's Workshop acquisition package."""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
PACKAGE_REL = Path("Plugins/Integrations/MerlinsWorkshop")
MODULE_REL = PACKAGE_REL / "Tools/merlins_workshop.py"
MANIFEST_REL = PACKAGE_REL / "merlin-source.json"
PLUGIN_REL = PACKAGE_REL / "plugin.json"
GOLDEN_REL = PACKAGE_REL / "Tests/Fixtures/git-lfs-work-order.json"
PACKAGE_TEST_REL = PACKAGE_REL / "Tests/test_merlins_workshop.py"
BRIDGE_REL = Path("Gems/TaintedGrailModdingSDK/Tools/tests/test_merlins_workshop.py")
CPP_REL = Path("Gems/TaintedGrailModdingSDK/Code/Source/GameInformationAcquisition.cpp")
CPP_TEST_REL = Path("Gems/TaintedGrailModdingSDK/Code/Tests/GameInformationAcquisitionTests.cpp")
DOC_REL = Path("docs/tainted-grail-sdk/MERLINS_WORKSHOP_PROVIDER.md")
PINNED_COMMIT = "073bdab3e09d6adad5003339fc49b021738d71e6"

REQUIRED_PACKAGE_FILES = {
    "README.md",
    "Tests/Fixtures/git-lfs-work-order.json",
    "Tests/test_merlins_workshop.py",
    "Tools/merlins_workshop.py",
    "merlin-source.json",
    "plugin.json",
}
FORBIDDEN_SUFFIXES = {
    ".7z",
    ".dll",
    ".exe",
    ".fbx",
    ".jpg",
    ".pdf",
    ".png",
    ".tga",
    ".unitypackage",
    ".wav",
    ".zip",
}
REQUIRED_SOURCE = (
    'REPOSITORY = "AR-Questline/merlin-workshop"',
    f'PINNED_COMMIT = "{PINNED_COMMIT}"',
    'PINNED_TAG = "v1.1.0"',
    'TOOL_VERSION = "1.1.0"',
    'UNITY_VERSION = "6000.0.60f1"',
    'ADDRESSABLES_VERSION = "2.7.4"',
    '"process_execution_allowed": False',
    '"network_execution_allowed": False',
    '"unity_launch_allowed": False',
    '"runtime_execution_allowed": False',
    '"github_autogenerated_zip_allowed": False',
    '"release_asset_route_allowed": False',
    '"execution_allowed": False',
    "parse_lfs_pointer",
    "git_blob_sha1",
    '".git/HEAD"',
    "must use the exact pinned commit in detached-HEAD form",
    '"private_checkout_path_recorded": False',
    '"qualified_for_observation": False',
    "Explicit operator licence acceptance is required",
)
FORBIDDEN_SOURCE = (
    "import requests",
    "import socket",
    "import subprocess",
    "import urllib.request",
    "os.system",
    "shell=True",
    "Popen(",
    "UnityEngine",
    "BepInEx",
    "Harmony",
    "Process.Start",
)


class MerlinsWorkshopValidationError(RuntimeError):
    """Raised when the reviewed optional Merlin provider drifts."""


def read_text(root: Path, relative: Path) -> str:
    try:
        return (root / relative).read_text(encoding="utf-8", errors="strict")
    except (OSError, UnicodeDecodeError) as exc:
        raise MerlinsWorkshopValidationError(
            f"Unable to read {relative.as_posix()}."
        ) from exc


def read_bytes(root: Path, relative: Path) -> bytes:
    try:
        return (root / relative).read_bytes()
    except OSError as exc:
        raise MerlinsWorkshopValidationError(
            f"Unable to read {relative.as_posix()}."
        ) from exc


def load_provider(root: Path):
    path = root / MODULE_REL
    spec = importlib.util.spec_from_file_location(
        "merlins_workshop_validation_target",
        path,
    )
    if spec is None or spec.loader is None:
        raise MerlinsWorkshopValidationError("Unable to load Merlin provider.")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
    except Exception as exc:
        raise MerlinsWorkshopValidationError(
            f"Unable to load Merlin provider: {exc}"
        ) from exc
    return module


def validate_package_tree(root: Path) -> None:
    package = root / PACKAGE_REL
    actual = {
        path.relative_to(package).as_posix()
        for path in package.rglob("*")
        if path.is_file()
        and "__pycache__" not in path.parts
        and path.suffix != ".pyc"
    }
    if actual != REQUIRED_PACKAGE_FILES:
        missing = sorted(REQUIRED_PACKAGE_FILES - actual)
        extra = sorted(actual - REQUIRED_PACKAGE_FILES)
        raise MerlinsWorkshopValidationError(
            "Merlin package file set drifted; missing="
            + ",".join(missing)
            + "; extra="
            + ",".join(extra)
        )
    for relative in sorted(actual):
        path = package / relative
        if path.is_symlink():
            raise MerlinsWorkshopValidationError(
                f"Tracked Merlin package path is a symlink: {relative}."
            )
        if path.suffix.lower() in FORBIDDEN_SUFFIXES:
            raise MerlinsWorkshopValidationError(
                f"Official or binary payload entered FOA-SDK: {relative}."
            )
        if path.stat().st_size > 2 * 1024 * 1024:
            raise MerlinsWorkshopValidationError(
                f"Merlin package source is unexpectedly large: {relative}."
            )


def validate_plugin(root: Path) -> None:
    try:
        plugin = json.loads(read_text(root, PLUGIN_REL))
    except json.JSONDecodeError as exc:
        raise MerlinsWorkshopValidationError("Merlin plugin.json is malformed.") from exc
    expected = {
        "capabilities",
        "category",
        "compatibility",
        "dependencies",
        "entry_points",
        "id",
        "name",
        "optional",
        "provenance",
        "schema_version",
        "status",
        "version",
    }
    if not isinstance(plugin, dict) or set(plugin) != expected:
        raise MerlinsWorkshopValidationError(
            "Merlin plugin.json differs from the governed schema surface."
        )
    checks = (
        plugin.get("schema_version") == 1,
        plugin.get("id") == "extension.merlins-workshop",
        plugin.get("category") == "integration",
        plugin.get("status") == "experimental",
        plugin.get("optional") is True,
        plugin.get("entry_points")
        == {
            "python_modules": ["Tools/merlins_workshop.py"],
            "tools": ["Tools/merlins_workshop.py"],
        },
        plugin.get("capabilities")
        == [
            "acquisition.merlin.checkout.verify",
            "acquisition.merlin.license.accept",
            "acquisition.merlin.plan",
            "acquisition.merlin.receipt.verify",
        ],
        plugin.get("dependencies") == [],
        plugin.get("compatibility")
        == {
            "branches": [],
            "game_versions": [],
            "runtime_targets": ["editor-only"],
        },
        plugin.get("provenance")
        == {
            "license": "Apache-2.0 OR MIT",
            "origin": "theb0yys/FOA-SDK",
            "redistribution_reviewed": True,
            "revision": "project-owned",
        },
    )
    if not all(checks):
        raise MerlinsWorkshopValidationError(
            "Merlin plugin identity, capability or provenance drifted."
        )


def validate_manifest_and_golden(root: Path) -> None:
    module = load_provider(root)
    try:
        manifest = module.load_manifest(root / MANIFEST_REL)
    except Exception as exc:
        raise MerlinsWorkshopValidationError(
            f"Merlin source manifest is invalid: {exc}"
        ) from exc
    expected_anchors = {
        ".gitattributes": "b214ce6c45182cb925d04e9e5a3270f94a8a917a",
        ".gitconfig.txt": "89345693e41693fb727e2e4315aac519f261cb4f",
        "Assets/CodeMod/ModInfo.cs": "e7d2bc4fc11d02a7c5fe7c5a5bdc4f83efdc623d",
        "Packages/manifest.json": "102800be839dd2134f9bf49fa863ae95d17139d0",
        "ProjectSettings/ProjectVersion.txt": "ea02f79eaf72328dc0ccebd3788b015e97ef3102",
        "README.md": "a0c23e60ed0f989144fe2ae52d53146b07b7db8e",
    }
    if {
        row["path"]: row["git_blob_sha1"] for row in manifest["anchors"]
    } != expected_anchors:
        raise MerlinsWorkshopValidationError(
            "Merlin exact source-anchor register drifted."
        )
    expected_licenses = {
        "LICENSE_EN.pdf": (
            "855f10a3d3807a75526a87e1ac395a78dea2509e",
            "225a4fc437fa2b6011c884ceb6258bab76e925820e7ef2a804d166fe16d854fd",
            488639,
        ),
        "LICENSE_PL.pdf": (
            "19bdfe5f455a28425a029f244f6f6ab97bad01d9",
            "e40bef65193c273dede4eecc422a4dd2d4be6bd36d8e239384fc853f7c5cf1b5",
            558453,
        ),
    }
    actual_licenses = {
        row["path"]: (
            row["git_blob_sha1"],
            row["lfs_sha256"],
            row["bytes"],
        )
        for row in manifest["licenses"]
    }
    if actual_licenses != expected_licenses:
        raise MerlinsWorkshopValidationError(
            "Merlin official licence LFS register drifted."
        )
    generated = module.canonical_json_bytes(module.build_work_order(manifest))
    if generated != read_bytes(root, GOLDEN_REL):
        raise MerlinsWorkshopValidationError(
            "Merlin Git/LFS work order is stale or non-deterministic."
        )


def validate_provider_source(root: Path) -> None:
    source = read_text(root, MODULE_REL)
    for fragment in REQUIRED_SOURCE:
        if fragment not in source:
            raise MerlinsWorkshopValidationError(
                f"Merlin provider is missing fail-closed behavior {fragment!r}."
            )
    for fragment in FORBIDDEN_SOURCE:
        if fragment in source:
            raise MerlinsWorkshopValidationError(
                f"Merlin provider contains forbidden execution/runtime code {fragment!r}."
            )
    for fragment in (
        "github.com/AR-Questline/merlin-workshop/archive/",
        "/main/",
        "/master/",
        "releases/latest",
        "refs/heads/",
    ):
        if fragment in source:
            raise MerlinsWorkshopValidationError(
                f"Merlin provider contains an unpinned acquisition route {fragment!r}."
            )


def validate_cpp_registry(root: Path) -> None:
    source = read_text(root, CPP_REL)
    for fragment in (
        'PinnedMerlinWorkshopCommit =',
        f'"{PINNED_COMMIT}"',
        'merlin.m_providerId = "provider.merlin-workshop";',
        "merlin.m_qualification = QualificationState::ExactInstallBound;",
        "merlin.m_sourceRevision = PinnedMerlinWorkshopCommit;",
        "merlin.m_licenseExpression =",
        '"LicenseRef-Merlins-Workshop-1.1.0";',
        "merlin.m_optional = true;",
        "merlin.m_requiresLocalFileRead = true;",
        "merlin.m_requiresNetwork = true;",
        "QualificationState::ExactInstallBound",
    ):
        if fragment not in source:
            raise MerlinsWorkshopValidationError(
                f"C++ acquisition registry is missing Merlin binding {fragment!r}."
            )
    tests = read_text(root, CPP_TEST_REL)
    for fragment in (
        "ExactMerlinObservationBuildsCandidateEvidence",
        "MerlinRevisionDriftFailsClosed",
        "MERLIN_QUALIFICATION_RECEIPT.json",
        "LicenseRef-Merlins-Workshop-1.1.0",
    ):
        if fragment not in tests:
            raise MerlinsWorkshopValidationError(
                f"Compiled Merlin acquisition coverage is missing {fragment!r}."
            )


def validate_tests_docs_and_gate(root: Path) -> None:
    package_tests = read_text(root, PACKAGE_TEST_REL)
    for fragment in (
        "test_work_order_is_deterministic_and_non_executable",
        "test_lfs_pointer_checkout_remains_blocked",
        "test_materialized_checkout_requires_explicit_acceptance",
        "test_symbolic_head_is_rejected",
        "test_symlinked_anchor_is_rejected",
        "test_receipt_tampering_is_rejected",
    ):
        if fragment not in package_tests:
            raise MerlinsWorkshopValidationError(
                f"Merlin provider tests are missing {fragment!r}."
            )
    bridge = read_text(root, BRIDGE_REL)
    for fragment in (
        "MerlinsWorkshop/Tests/test_merlins_workshop.py",
        "load_tests",
        "MerlinsWorkshopTests",
    ):
        if fragment not in bridge:
            raise MerlinsWorkshopValidationError(
                f"Mandatory Merlin test bridge is missing {fragment!r}."
            )
    public = read_text(root, DOC_REL)
    for fragment in (
        "1.1.0",
        PINNED_COMMIT,
        "6000.0.60f1",
        "2.7.4",
        "Git LFS",
        "autogenerated ZIP",
        "operator licence acceptance",
        "no process execution",
        "candidate observation",
        "Mono",
        "IL2CPP",
    ):
        if fragment not in public:
            raise MerlinsWorkshopValidationError(
                f"Public Merlin contract is missing {fragment!r}."
            )
    if "MerlinsWorkshop" not in read_text(
        root,
        Path("Plugins/Integrations/README.md"),
    ):
        raise MerlinsWorkshopValidationError(
            "Integration package index does not list MerlinsWorkshop."
        )


def validate_merlins_workshop(repo_root: Path = REPO_ROOT) -> None:
    validate_package_tree(repo_root)
    validate_plugin(repo_root)
    validate_provider_source(repo_root)
    validate_manifest_and_golden(repo_root)
    validate_cpp_registry(repo_root)
    validate_tests_docs_and_gate(repo_root)


def main() -> int:
    try:
        validate_merlins_workshop()
    except MerlinsWorkshopValidationError as exc:
        print(f"Merlin's Workshop validation failed: {exc}", file=sys.stderr)
        return 1
    print("Optional Merlin's Workshop acquisition validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
