#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#

set(FILES
    Source/AdapterBuildManifestService.cpp
    Source/AdapterBuildManifestService.h
    Source/AdapterBuildManifestServicePart1.inl
    Source/AdapterBuildManifestServicePart2.inl
    Source/AdapterBuildManifestServicePart3.inl
    Source/AdapterCompatibilityService.cpp
    Source/AdapterCompatibilityService.h
    Source/AdapterContractRegistry.cpp
    Source/AdapterContractRegistry.h
    Source/AdapterPackageAssemblyPreviewService.cpp
    Source/AdapterPackageAssemblyPreviewService.h
    Source/AdapterPackageAssemblyPreviewServicePart1.inl
    Source/AdapterPackageAssemblyPreviewServicePart2.inl
    Source/AdapterPackageAssemblyPreviewServicePart3.inl
    Source/AdapterRuntimeResultContracts.cpp
    Source/AdapterRuntimeResultContracts.h
    Source/AdapterRuntimeResultEvidenceService.cpp
    Source/AdapterRuntimeResultEvidenceService.h
    Source/AdapterRuntimeResultEvidenceServicePart1.inl
    Source/AdapterRuntimeResultEvidenceServicePart2.inl
    Source/AdapterRuntimeResultEvidenceServicePart3.inl
    Source/AdapterWorkOrderPlanningService.cpp
    Source/AdapterWorkOrderPlanningServicePart1.inl
    Source/AdapterWorkOrderPlanningServicePart2.inl
    Source/AdapterWorkOrderPlanningServicePart3.inl
    Source/AdapterWorkOrderPlanningServicePart4.inl
    Source/AdapterWorkOrderPlanningServicePart5.inl
    Source/AdapterWorkOrderPlanningServicePart6.inl
    Source/AdapterWorkOrderPlanningServicePart7.inl
    Source/AdapterWorkOrderPlanningServicePart8.inl
    Source/AdapterWorkOrderPlanningServicePart9.inl
    Source/AdapterWorkOrderPlanningService.h
    Source/CatalogDatabase.cpp
    Source/CatalogDatabase.h
    Source/CatalogGovernanceBlockerService.cpp
    Source/CatalogGovernanceBlockerService.h
    Source/CatalogGovernanceTypes.cpp
    Source/CatalogGovernanceTypes.h
    Source/CatalogTransactionService.cpp
    Source/CatalogTransactionService.h
    Source/EconomyBlockerService.cpp
    Source/EconomyBlockerService.h
    Source/EconomyCoverageService.cpp
    Source/EconomyCoverageService.h
    Source/EconomyDuplicateDetectionService.cpp
    Source/EconomyDuplicateDetectionService.h
    Source/EconomyModels.cpp
    Source/EconomyModels.h
    Source/FoundationModels.cpp
    Source/FoundationModels.h
    Source/FoundationValidationService.cpp
    Source/FoundationValidationService.h
    Source/SourceEvidenceRegistry.cpp
    Source/SourceEvidenceRegistry.h
)
