#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#

set(FILES
    Source/AdapterBuildManifestService.cpp
    Source/AdapterBuildManifestService.h
    Source/AdapterBuildManifestServicePart1.inl
    Source/AdapterBuildManifestServicePart2.inl
    Source/AdapterBuildManifestServicePart3.inl
    Source/AdapterCompatibilityService.cpp
    Source/AdapterCompatibilityService.h
    Source/AdapterContractRegistry.cpp
    Source/AdapterContractRegistry.h
    Source/AdapterDeploymentExecutionEvidenceService.cpp
    Source/AdapterDeploymentExecutionEvidenceService.h
    Source/AdapterDeploymentExecutionEvidenceServicePart1.inl
    Source/AdapterDeploymentExecutionEvidenceServicePart2.inl
    Source/AdapterDeploymentExecutionEvidenceServicePart3.inl
    Source/AdapterDeploymentExecutionResultCanonical.cpp
    Source/AdapterDeploymentExecutionResultCanonical.h
    Source/AdapterDeploymentExecutionResultContracts.cpp
    Source/AdapterDeploymentExecutionResultContracts.h
    Source/AdapterDeploymentWorkOrderService.cpp
    Source/AdapterDeploymentWorkOrderService.h
    Source/AdapterDeploymentWorkOrderServicePart1.inl
    Source/AdapterDeploymentWorkOrderServicePart2.inl
    Source/AdapterDeploymentWorkOrderServicePart3.inl
    Source/AdapterPackageAssemblyPreviewService.cpp
    Source/AdapterPackageAssemblyPreviewService.h
    Source/AdapterPackageAssemblyPreviewServicePart1.inl
    Source/AdapterPackageAssemblyPreviewServicePart2.inl
    Source/AdapterPackageAssemblyPreviewServicePart3.inl
    Source/AdapterPostDeploymentVerificationContracts.cpp
    Source/AdapterPostDeploymentVerificationContracts.h
    Source/AdapterPostDeploymentVerificationService.cpp
    Source/AdapterPostDeploymentVerificationService.h
    Source/AdapterPostDeploymentVerificationServicePart1.inl
    Source/AdapterPostDeploymentVerificationServicePart2.inl
    Source/AdapterPostDeploymentVerificationServicePart3.inl
    Source/AdapterPostDeploymentVerifierContracts.cpp
    Source/AdapterPostDeploymentVerifierContracts.h
    Source/AdapterPostDeploymentVerifierEvidenceService.cpp
    Source/AdapterPostDeploymentVerifierEvidenceService.h
    Source/AdapterPostDeploymentVerifierEvidenceServicePart1.inl
    Source/AdapterPostDeploymentVerifierEvidenceServicePart2.inl
    Source/AdapterPostDeploymentVerifierEvidenceServicePart3.inl
    Source/AdapterPostDeploymentVerifierEvidenceServicePart4.inl
    Source/AdapterPostDeploymentVerifierEvidenceServicePart5.inl
    Source/AdapterPostDeploymentVerifierEvidenceServicePart6.inl
    Source/AdapterPostDeploymentVerifierResultCanonical.cpp
    Source/AdapterPostDeploymentVerifierResultCanonical.h
    Source/AdapterReleaseArtifactContracts.cpp
    Source/AdapterReleaseArtifactContracts.h
    Source/AdapterReleaseArtifactProvenanceService.cpp
    Source/AdapterReleaseArtifactProvenanceService.h
    Source/AdapterReleaseArtifactProvenanceServicePart1.inl
    Source/AdapterReleaseArtifactProvenanceServicePart2.inl
    Source/AdapterReleaseAssemblyEvidenceService.cpp
    Source/AdapterReleaseAssemblyEvidenceService.h
    Source/AdapterReleaseAssemblyResultContracts.cpp
    Source/AdapterReleaseAssemblyResultContracts.h
    Source/AdapterReleaseSigningEvidenceService.cpp
    Source/AdapterReleaseSigningEvidenceService.h
    Source/AdapterReleaseSigningResultContracts.cpp
    Source/AdapterReleaseSigningResultContracts.h
    Source/AdapterRuntimeResultCanonical.cpp
    Source/AdapterRuntimeResultCanonical.h
    Source/AdapterRuntimeResultContracts.cpp
    Source/AdapterRuntimeResultContracts.h
    Source/AdapterRuntimeResultEvidenceService.cpp
    Source/AdapterRuntimeResultEvidenceService.h
    Source/AdapterRuntimeResultEvidenceServicePart1.inl
    Source/AdapterRuntimeResultEvidenceServicePart2.inl
    Source/AdapterRuntimeResultEvidenceServicePart3.inl
    Source/AdapterStagingDeploymentPreviewService.cpp
    Source/AdapterStagingDeploymentPreviewService.h
    Source/AdapterStagingDeploymentPreviewServicePart1.inl
    Source/AdapterStagingDeploymentPreviewServicePart2.inl
    Source/AdapterStagingDeploymentPreviewServicePart3.inl
    Source/AdapterVerifierEvidenceReconciliationContracts.cpp
    Source/AdapterVerifierEvidenceReconciliationContracts.h
    Source/AdapterVerifierEvidenceReconciliationService.cpp
    Source/AdapterVerifierEvidenceReconciliationService.h
    Source/AdapterVerifierEvidenceReconciliationServicePart1.inl
    Source/AdapterVerifierEvidenceReconciliationServicePart2.inl
    Source/AdapterVerifierEvidenceReconciliationServicePart3.inl
    Source/AdapterVerifierEvidenceReconciliationServicePart4.inl
    Source/AdapterWorkOrderPlanningService.cpp
    Source/AdapterWorkOrderPlanningServicePart1.inl
    Source/AdapterWorkOrderPlanningServicePart2.inl
    Source/AdapterWorkOrderPlanningServicePart3.inl
    Source/AdapterWorkOrderPlanningServicePart4.inl
    Source/AdapterWorkOrderPlanningServicePart5.inl
    Source/AdapterWorkOrderPlanningServicePart6.inl
    Source/AdapterWorkOrderPlanningServicePart7.inl
    Source/AdapterWorkOrderPlanningServicePart8.inl
    Source/AdapterWorkOrderPlanningServicePart9.inl
    Source/AdapterWorkOrderPlanningService.h
    Source/CanonicalFingerprint.cpp
    Source/CanonicalFingerprint.h
    Source/DeterministicContractJson.h
    Source/CatalogDatabase.cpp
    Source/CatalogDatabase.h
    Source/CatalogDatabaseBase.inl
    Source/CatalogDatabaseIntegrity.cpp
    Source/CatabaseIntegrityBase.inl
    Source/CatalogDatabasePopulation.cpp
    Source/CatalogDatabasePopulationPart1.inl
    Source/CatalogDatabasePopulationPart2.inl
    Source/CatalogDatabasePopulationPart3.inl
    Source/CatalogGovernanceBlockerService.cpp
    Source/CatalogGovernanceBlockerService.h
    Source/CatalogGovernanceTypes.cpp
    Source/CatalogGovernanceTypes.h
    Source/CatalogTransactionService.cpp
    Source/CatalogTransactionService.h
    Source/EconomyBlockerService.cpp
    Source/EconomyBlockerService.h
    Source/EconomyCoverageService.cpp
    Source/EconomyCoverageService.h
    Source/EconomyDuplicateDetectionService.cpp
    Source/EconomyDuplicateDetectionService.h
    Source/EconomyModels.cpp
    Source/EconomyModels.h
    Source/FoundationModels.cpp
    Source/FoundationModels.h
    Source/PackagePathValidation.cpp
    Source/PackagePathValidation.h
    Source/PopulationModels.cpp
    Source/PopulationModels.h
    Source/ResearchContractValidation.cpp
    Source/ResearchContractValidation.h
    Source/SourceEvidenceRegistry.cpp
    Source/SourceEvidenceRegistry.h
)

# Core contract implementations deliberately use file-local helper names. Keep
# each implementation in its own translation unit so unity concatenation cannot
# merge unrelated anonymous namespaces or hide missing direct includes.
set(SKIP_UNITY_BUILD_INCLUSION_FILES)
foreach(source_file IN LISTS FILES)
    if(source_file MATCHES "\\.cpp$")
        list(APPEND SKIP_UNITY_BUILD_INCLUSION_FILES ${subce_file})
    endif()
endforeach()
