from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path

MODULE_PATH = Path(__file__).resolve().parents[1] / "Tools/merlins_workshop.py"
SPEC = importlib.util.spec_from_file_location("merlins_workshop_test_target", MODULE_PATH)
assert SPEC and SPEC.loader
merlin = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = merlin
SPEC.loader.exec_module(merlin)


def canonical(value: object) -> bytes:
    return (json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n").encode()


def lfs_pointer(payload: bytes) -> bytes:
    return (
        "version https://git-lfs.github.com/spec/v1\n"
        f"oid sha256:{hashlib.sha256(payload).hexdigest()}\n"
        f"size {len(payload)}\n"
    ).encode()


class MerlinsWorkshopTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        self.checkout = self.root / "checkout"
        (self.checkout / ".git").mkdir(parents=True)
        (self.checkout / ".git/HEAD").write_text(merlin.PINNED_COMMIT + "\n", encoding="ascii")
        self.anchor_payload = b"official anchor\n"
        (self.checkout / "README.md").write_bytes(self.anchor_payload)
        self.license_en = b"%PDF-1.7\nEnglish licence fixture\n"
        self.license_pl = b"%PDF-1.7\nPolish licence fixture\n"
        self.manifest_path = self.root / "merlin-source.json"
        self.write_manifest()

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def write_manifest(self) -> None:
        document = {
            "anchors": [
                {
                    "git_blob_sha1": merlin.git_blob_sha1(self.anchor_payload),
                    "path": "README.md",
                }
            ],
            "authority": dict(merlin.AUTHORITY),
            "licenses": [
                {
                    "bytes": len(self.license_en),
                    "git_blob_sha1": merlin.git_blob_sha1(lfs_pointer(self.license_en)),
                    "lfs_sha256": hashlib.sha256(self.license_en).hexdigest(),
                    "path": "LICENSE_EN.pdf",
                },
                {
                    "bytes": len(self.license_pl),
                    "git_blob_sha1": merlin.git_blob_sha1(lfs_pointer(self.license_pl)),
                    "lfs_sha256": hashlib.sha256(self.license_pl).hexdigest(),
                    "path": "LICENSE_PL.pdf",
                },
            ],
            "provider_id": merlin.PROVIDER_ID,
            "schema_version": 1,
            "source": {
                "commit": merlin.PINNED_COMMIT,
                "license_expression": merlin.LICENSE_EXPRESSION,
                "release": merlin.TOOL_VERSION,
                "repository": merlin.REPOSITORY,
                "tag": merlin.PINNED_TAG,
            },
            "toolchain": {
                "addressables": merlin.ADDRESSABLES_VERSION,
                "unity_editor": merlin.UNITY_VERSION,
                "unity_revision": merlin.UNITY_REVISION,
            },
        }
        self.manifest_path.write_bytes(canonical(document))

    def materialize_licenses(self) -> None:
        (self.checkout / "LICENSE_EN.pdf").write_bytes(self.license_en)
        (self.checkout / "LICENSE_PL.pdf").write_bytes(self.license_pl)

    def write_license_pointers(self) -> None:
        (self.checkout / "LICENSE_EN.pdf").write_bytes(lfs_pointer(self.license_en))
        (self.checkout / "LICENSE_PL.pdf").write_bytes(lfs_pointer(self.license_pl))

    def test_work_order_is_deterministic_and_non_executable(self) -> None:
        manifest = merlin.load_manifest(self.manifest_path)
        first = merlin.build_work_order(manifest)
        second = merlin.build_work_order(manifest)
        self.assertEqual(first, second)
        self.assertEqual(first["source"]["commit"], merlin.PINNED_COMMIT)
        self.assertFalse(first["github_autogenerated_zip_allowed"])
        self.assertFalse(first["release_asset_route_allowed"])
        self.assertTrue(all(step["execution_allowed"] is False for step in first["steps"]))
        self.assertTrue(all(merlin.DESTINATION_TOKEN in step["argv"] for step in first["steps"]))

    def test_lfs_pointer_checkout_remains_blocked(self) -> None:
        self.write_license_pointers()
        receipt = merlin.inspect_checkout(self.checkout, merlin.load_manifest(self.manifest_path))
        self.assertEqual(receipt["qualification"], "blocked_lfs_materialization_required")
        self.assertFalse(receipt["qualified_for_observation"])
        self.assertTrue(all(row["materialized"] is False for row in receipt["licenses"]))

    def test_materialized_checkout_requires_explicit_acceptance(self) -> None:
        self.materialize_licenses()
        receipt = merlin.inspect_checkout(self.checkout, merlin.load_manifest(self.manifest_path))
        self.assertEqual(receipt["qualification"], "ready_for_operator_license_acceptance")
        with self.assertRaisesRegex(merlin.MerlinAcquisitionError, "acceptance"):
            merlin.accept_license(receipt, accepted=False)
        accepted = merlin.accept_license(receipt, accepted=True)
        self.assertTrue(accepted["qualified_for_observation"])
        self.assertTrue(accepted["license_acceptance_recorded"])
        merlin.verify_receipt(accepted)

    def test_symbolic_head_is_rejected(self) -> None:
        self.materialize_licenses()
        (self.checkout / ".git/HEAD").write_text("ref: refs/heads/main\n", encoding="ascii")
        with self.assertRaisesRegex(merlin.MerlinAcquisitionError, "detached-HEAD"):
            merlin.inspect_checkout(self.checkout, merlin.load_manifest(self.manifest_path))

    def test_anchor_tampering_is_rejected(self) -> None:
        self.materialize_licenses()
        (self.checkout / "README.md").write_bytes(b"tampered")
        with self.assertRaisesRegex(merlin.MerlinAcquisitionError, "anchor differs"):
            merlin.inspect_checkout(self.checkout, merlin.load_manifest(self.manifest_path))

    @unittest.skipUnless(hasattr(os, "symlink"), "symlinks unavailable")
    def test_symlinked_anchor_is_rejected(self) -> None:
        self.materialize_licenses()
        target = self.checkout / "real-readme"
        target.write_bytes(self.anchor_payload)
        (self.checkout / "README.md").unlink()
        os.symlink(target, self.checkout / "README.md")
        with self.assertRaisesRegex(merlin.MerlinAcquisitionError, "symlink"):
            merlin.inspect_checkout(self.checkout, merlin.load_manifest(self.manifest_path))

    def test_receipt_tampering_is_rejected(self) -> None:
        self.materialize_licenses()
        receipt = merlin.accept_license(
            merlin.inspect_checkout(self.checkout, merlin.load_manifest(self.manifest_path)),
            accepted=True,
        )
        receipt["authority"]["runtime_execution_allowed"] = True
        with self.assertRaisesRegex(merlin.MerlinAcquisitionError, "identity|authority"):
            merlin.verify_receipt(receipt)

    def test_production_manifest_matches_committed_golden(self) -> None:
        production_manifest = merlin.load_manifest()
        generated = merlin.canonical_json_bytes(merlin.build_work_order(production_manifest))
        golden = Path(__file__).resolve().parent / "Fixtures/git-lfs-work-order.json"
        self.assertEqual(generated, golden.read_bytes())
        self.assertEqual(production_manifest["source"]["commit"], merlin.PINNED_COMMIT)
        self.assertEqual(production_manifest["toolchain"]["unity_editor"], "6000.0.60f1")


if __name__ == "__main__":
    unittest.main()
